name: ContainerTracker
version: '${project.version}'
main: com.emicb.containertracker.ContainerTracker
api-version: 1.20
depend: [ProtocolLib]
commands:
  ct-toggle-debug:
    description: toggles debug mode for ContainerTracker
    usage: /<command>
  puzzle-progress:
    description: allows players to see what puzzles others have solved
    usage: /<command>